{"name": "Проверяем что невозможно авторизоваться при отправке некорректных данных. Возвращается сообщение об ошибке, статус ответа 404", "status": "passed", "steps": [{"name": "Логинимся курьером", "status": "passed", "parameters": [{"name": "login", "value": "'incorrect_data'"}, {"name": "password", "value": "'xscwbcbjby'"}], "start": 1733843408167, "stop": 1733843408371}], "parameters": [{"name": "field_name", "value": "'login'"}], "start": 1733843408167, "stop": 1733843408372, "uuid": "f7fa45bf-8e47-44c2-a5f8-d5e393efa00d", "historyId": "622bbe5c82f55c413bbf6fa850ea6e8b", "testCaseId": "62de0a1455e4348f76fb13991ea19ed5", "fullName": "tests.couriers.test_login_courier.TestLoginCourier#test_login_courier_with_incorrect_login_or_password", "labels": [{"name": "parentSuite", "value": "tests.couriers"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-4B15D1P"}, {"name": "thread", "value": "8004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.couriers.test_login_courier"}]}