{"name": "Проверяем что невозможно авторизоваться при отправке некорректных данных. Возвращается сообщение об ошибке, статус ответа 404", "status": "passed", "steps": [{"name": "Логинимся курьером", "status": "passed", "parameters": [{"name": "login", "value": "'fhbqplaebo'"}, {"name": "password", "value": "'incorrect_data'"}], "start": 1733843408962, "stop": 1733843409198}], "parameters": [{"name": "field_name", "value": "'password'"}], "start": 1733843408961, "stop": 1733843409198, "uuid": "0ae2b337-641c-4bf3-b14f-83341ed82ef5", "historyId": "78bd892d92288947a085d1996bcd5f2b", "testCaseId": "62de0a1455e4348f76fb13991ea19ed5", "fullName": "tests.couriers.test_login_courier.TestLoginCourier#test_login_courier_with_incorrect_login_or_password", "labels": [{"name": "parentSuite", "value": "tests.couriers"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-4B15D1P"}, {"name": "thread", "value": "8004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.couriers.test_login_courier"}]}